[package]
name = "line_art"
version = "0.1.0"
edition = "2024"

[dependencies]
pyxel-engine = { path = "../pyxel/rust/pyxel-engine" }

[features]
sdl2 = ["pyxel-engine/sdl2"]
sdl2_bundle = ["pyxel-engine/sdl2_bundle"]